# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conver_xy.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 20, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 83, 171, 41))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.sourceLabel_path_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.sourceLabel_path_edit.setGeometry(QtCore.QRect(229, 90, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sourceLabel_path_edit.setFont(font)
        self.sourceLabel_path_edit.setObjectName("sourceLabel_path_edit")
        self.sourceLabel_btn = QtWidgets.QPushButton(self.centralwidget)
        self.sourceLabel_btn.setGeometry(QtCore.QRect(682, 90, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sourceLabel_btn.setFont(font)
        self.sourceLabel_btn.setObjectName("sourceLabel_btn")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(19, 141, 201, 41))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.grayValue_path_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.grayValue_path_edit.setGeometry(QtCore.QRect(230, 146, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.grayValue_path_edit.setFont(font)
        self.grayValue_path_edit.setObjectName("grayValue_path_edit")
        self.HF_source_path_btn = QtWidgets.QPushButton(self.centralwidget)
        self.HF_source_path_btn.setGeometry(QtCore.QRect(682, 146, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.HF_source_path_btn.setFont(font)
        self.HF_source_path_btn.setObjectName("HF_source_path_btn")
        self.conver_coordinate = QtWidgets.QPushButton(self.centralwidget)
        self.conver_coordinate.setGeometry(QtCore.QRect(367, 207, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.conver_coordinate.setFont(font)
        self.conver_coordinate.setObjectName("conver_coordinate")
        self.convert_process_label = QtWidgets.QLabel(self.centralwidget)
        self.convert_process_label.setGeometry(QtCore.QRect(200, 280, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.convert_process_label.setFont(font)
        self.convert_process_label.setText("")
        self.convert_process_label.setAlignment(QtCore.Qt.AlignCenter)
        self.convert_process_label.setObjectName("convert_process_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "X Y Z 坐标校正"))
        self.label_2.setText(_translate("MainWindow", "原始标注数据文件夹"))
        self.sourceLabel_btn.setText(_translate("MainWindow", "选择"))
        self.label_3.setText(_translate("MainWindow", "HouseField数据文件夹"))
        self.HF_source_path_btn.setText(_translate("MainWindow", "选择"))
        self.conver_coordinate.setText(_translate("MainWindow", "坐标校正"))

